// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParsedData.DAL;

namespace ParsedData.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201108175249_Create Db2")]
    partial class CreateDb2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("ParsedData.Models.TaskData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStateId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaskDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 16GB",
                            LastUpdate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S2",
                            State = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 32GB",
                            LastUpdate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S3",
                            State = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 64GB",
                            LastUpdate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S4",
                            State = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB",
                            LastUpdate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S5",
                            State = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB",
                            LastUpdate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S6",
                            State = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB",
                            LastUpdate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S7",
                            State = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 64GB",
                            LastUpdate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S8",
                            State = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 32GB White",
                            LastUpdate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S9",
                            State = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 64GB Red",
                            LastUpdate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S10",
                            State = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB Ultra",
                            LastUpdate = new DateTime(2019, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S11",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB black",
                            LastUpdate = new DateTime(2019, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S20",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2019, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Smartphone 128GB light",
                            LastUpdate = new DateTime(2019, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S21",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 16GB",
                            LastUpdate = new DateTime(2019, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 2",
                            State = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 16GB",
                            LastUpdate = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 3",
                            State = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 16GB",
                            LastUpdate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 4",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB",
                            LastUpdate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 5",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB",
                            LastUpdate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 6",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB",
                            LastUpdate = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 7",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2019, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 64GB",
                            LastUpdate = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 8",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 32GB White",
                            LastUpdate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 9",
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 64GB Red",
                            LastUpdate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 10",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2019, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB Ultra",
                            LastUpdate = new DateTime(2019, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 11",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2019, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB black",
                            LastUpdate = new DateTime(2019, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 12",
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2019, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataStateId = 3,
                            Description = "Xiaomi Note plus 128GB light",
                            LastUpdate = new DateTime(2019, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi Note plus 13",
                            State = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ParsedData.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivan",
                            Sername = "Ivanov",
                            State = 0,
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdate = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vasiliy",
                            Sername = "Vasya",
                            State = 0,
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdate = new DateTime(2020, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nekrasov",
                            Sername = "Nikolya",
                            State = 0,
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2020, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdate = new DateTime(2020, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Кисилёв",
                            Sername = "Дмитрий",
                            State = 0,
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2020, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Нагиев",
                            Sername = "Юрий",
                            State = 0,
                            StateId = 1
                        });
                });

            modelBuilder.Entity("ParsedData.Models.TaskData", b =>
                {
                    b.HasOne("ParsedData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
